### ISSUE TITLE
Arduino 2.3.2 setup

### ISSUE THREAD

**Issue by W4KRL** [ropg/heltec_esp32_lora_v3#13]
Your instructions say "Once that's done, you can go to the "Tools / Board" menu and select either of our two supported boards from the "Heltec (unofficial)" sub-menu."

This was not what I experienced.  Heltec (unofficial) was not in the dropdown until I installed Heltec (unofficial) v1.1.5 with Tools | Board Manager...

**Comment by recklessop** [comment]
agree, After adding the board URL I also needed to install the board library. Docs just need updated.

**Comment by ropg** [comment]
I'm testing a new method of adding the board definitions. Pease check out #14 if you want to help test it.
