### ISSUE TITLE
Not compatible with esp32 3.0.0-rc1 library?

### ISSUE THREAD

**Issue by ademars** [ropg/heltec_esp32_lora_v3#23]
Is the library supposed to work with the current esp32 3.0.0-rc1 libraries? I’m having runtime crashes:

Rebooting...
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x29 (SPI_FAST_FLASH_BOOT)
Saved PC:0x40377b35
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3818,len:0x508
load:0x403c9700,len:0x4
load:0x403c9704,len:0xad0
load:0x403cc700,len:0x29d8
entry 0x403c9880
E (108) tsens: CONFLICT! driver_ng is not allowed to be used with the legacy driver

abort() was called at PC 0x4201037f on core 0

Backtrace: 0x40377526:0x3fceb200 0x4037d1f5:0x3fceb220 0x40382e19:0x3fceb240 0x4201037f:0x3fceb2c0 0x42014f26:0x3fceb2e0 0x40377827:0x3fceb310 0x403cd856:0x3fceb340 0x403cdafe:0x3fceb380 0x403c98d5:0x3fceb4b0 0x40045c01:0x3fceb570 |<-CORRUPTED

ELF file SHA256: 5ac52b23e29f8286

**Comment by ropg** [comment]
"tsens: CONFLICT! driver_ng is not allowed to be used with the legacy driver"

Ah, that would be the temperature sensor code. I'll fix that with an #ifdef. But until then as a workaround if you do not need ESP32 chip temperature, just comment out the entire function `float heltec_temperature()`

Please try again and let me know if that's all that needs fixing.

**Comment by ademars** [comment]
That fixed the infinite boot loop. Thanks! The LoRa_rx_tx sketch now builds, runs, and interoperates with the heltec provided “WiFi_LoRa_32_V3_FactoryTest“ sketch. However, it appears that the “heltec_led” API isn’t working. The led never comes on. If I simply use digitalWrite(LED, 1/0), I see the led blink on each transmit. AlanOn May 17, 2024, at 1:04 AM, Rop Gonggrijp ***@***.***> wrote:﻿
"tsens: CONFLICT! driver_ng is not allowed to be used with the legacy driver"
Ah, that would be the temperature sensor code. I'll fix that with an #ifdef. But until then as a workaround if you do not need ESP32 chip temperature, just comment out the entire function float heltec_temperature()
Please try again and let me know if that's all that needs fixing.

**Comment by Velocet** [comment]
Please use [LED Control (LEDC)](https://espressif-docs.readthedocs-hosted.com/projects/arduino-esp32/en/latest/api/ledc.html)

**Comment by ropg** [comment]
In new version 0.9.0 I just released, both temperature sensing and LED driver were fixed to work with both v2.0.16 and v3.0.0 of ESP32 Arduino.
