### ISSUE TITLE
Arduino IDE sez "modules/SX126x/patches/SX126x_patch_scan.h: No such file or directory"

### ISSUE THREAD

**Issue by ZachreyNM** [ropg/heltec_esp32_lora_v3#3]
I hope this is right place to post this! I'm pretty new to github.

I just installed this library on Arduino IDE 1.8.19 on Linux.

I tried to compile the spectrum_analyzer and it bonked, saying:
"modules/SX126x/patches/SX126x_patch_scan.h: No such file or directory"

Is there something else I need to install to get it working?

**Comment by ropg** [comment]
Whoops. You're absolutely right. A mistake was made by not updating the #include for the patch file when I changed from depending on radioLib to (temporarily) using my own fork of it. Fixed in 0.3.4, released just now. :)
