### ISSUE TITLE
Heltec alternative lora boards?

### ISSUE THREAD

**Issue by treanus** [ropg/heltec_esp32_lora_v3#37]
Any change this library will work with [this Heltec Lora board](https://heltec.org/project/wireless-paper/)? Seems to have same MCU and Lora chip. 

Or even with the [Vision Master series](https://heltec.org/project/vision-master-t190/)?

Ps: Many thx for this great library, already use it to monitor the water level of a remote reservoir using two WiFi LoRa 32(V3).

**Comment by ropg** [comment]
Probably not as various pins and other aspects of the hardware will be different. But I'm sure you can adapt it to your use somehow.

See the README:

<img width="989" alt="image" src="https://github.com/user-attachments/assets/9817f8de-aefd-439a-a2aa-96ab847ae133">
