### ISSUE TITLE
lpp cayenne error with multiple channel

### ISSUE THREAD

**Issue by serpentRenard** [ropg/heltec_esp32_lora_v3#38]
got error  "sendReceive returned error -1114, we'll try again later."

when trying to add multiple lpp cayenne item into the same buffer.

state = node->sendReceive(lpp.getBuffer(), lpp.getSize(), 1, downlinkData, &lenDown);

one channel is working well
but the error apear with two lpp

lpp.addGPS(1,45.68,-73.52,15.2);   //firts
//lpp.addAnalogInput(2, 25.5);     //second   error with this line

the buffer is enough gig (working with other lib without issues)  
CayenneLPP lpp(50); 

My guess is the senReceive have a kind of buffer size limitation

**Comment by ropg** [comment]
This is internal to the LoRaWAN code in RadioLib. I suggest you [file the issue there](https://github.com/jgromes/RadioLib/issues).
