### ISSUE TITLE
Heltec WiFi LoRa 32(V3) / Wireless shell(V3) not in the list of boards 

### ISSUE THREAD

**Issue by probert100** [ropg/heltec_esp32_lora_v3#42]
Did I miss something if I don't see "Heltec WiFi LoRa 32(V3) / Wireless shell(V3)" in the list of the boards?
I see "Heltec WiFi LoRa 32(V3)"  

<img width="723" alt="image" src="https://github.com/user-attachments/assets/78a0aebf-715a-4a54-91fc-b53d14949cd4">

I believe I followed all of the instructions, but any example I try using the debugger  I get this  error: `Error: esp_usb_jtag: could not find or open device!`  Get Board Info returns basic information and when I plug it/unplug it. Serial Monitor shows state changes.

(uploading the examples to the board works)
I guess this may not be a real problem   I just don't know if the debugger should work at all with Heltec LoRa 32 (V3)

**Comment by probert100** [comment]
I was able to figure out what my problem was.

**Comment by KonRoz** [comment]
Which board did you end up using? I don't see "Heltec WiFi LoRa 32(V3) / Wireless shell(V3)" either.
