### ISSUE TITLE
wrong schematic diagram for Stick_V3

### ISSUE THREAD

**Issue by aintgotnoname** [ropg/heltec_esp32_lora_v3#5]
I believe the correct schematic can be found here:
https://resource.heltec.cn/download/Wireless_Stick_V3/HTIT-WS_V3_Schematic_Diagram.pdf

referenced from this site:
https://docs.heltec.cn/en/node/esp32/hardware_update_log.html#id4

Again, that you.

**Comment by aintgotnoname** [comment]
This is getting far afield from your library, and I apologize.

The meshatastic site refers to a version V3.1 and provides a link to its schematic.
https://meshtastic.org/docs/hardware/devices/heltec/
https://resource.heltec.cn/download/WiFi_LoRa_32_V3/HTIT-WB32LA(F)_V3.1_Schematic_Diagram.pdf

**Comment by ropg** [comment]
(Thanks BTW... !)

**Comment by aintgotnoname** [comment]
I'm not an authority.  It is a shame that the Heltec site itself doesn't reference the change/update.  Best I can do is quote the Meshtastic site mentioned earlier:

V3.1 differences   Firmware remains the same as V3 below. Compare schematics: 
  [V3.0]   https://web.archive.org/web/20221127054612/https://resource.heltec.cn/download/WiFi_LoRa32_V3/HTIT-WB32LA(F)_V3_Schematic_Diagram.pdf
 and [V3.1]  https://resource.heltec.cn/download/WiFi_LoRa_32_V3/HTIT-WB32LA(F)_V3.1_Schematic_Diagram.pdf

Key differences:

    Removal of [FDG6322C] (https://www.mouser.com/datasheet/2/308/1/FDG6322C_D-2312203.pdf) (a dual N & P channel FET) from the V3.1 power supply.

    Antenna filter values in V3.1 (L11 = 1.8pF, C15 = 2.7nH, C24 = 1.8pF) align more closely with ESP32-S3 reference design than V3.0 (L11 = 1.6nH, C15 = 6.9pF, C24 = 2.4pF).

It seems to me that your original schematics were for a V1 or V2.  I suspect this given the part numbers called out for the ESP and LoRa devices.  They seem to match the earlier board versions, but not the V3(.x).

My version of the Stick turns out to be a V3.1 as silk screened on the back side.  (Oh, and platformio defines the LED pin as a non-sensical pin 95.  *sigh* )

**Comment by ropg** [comment]
Mine also says v3.1 on the back. The thing that threw me most on the stick in general is that the display is powered by the "external" power supply. Once I figured it out, I noticed it says right there in the schematic, but then you have to know what you're looking for.

I'm thinking of making my own board definition files, so I can offer two boards: the regular and the stick, and set the appropriate preprocessor defines. Could even make options for button as power switch and other options I have, much like theirs has all these lora settings in there. Would have to figure out what the minimum thing to publich is, and would prefer it if this repo could then also be the board manager URL to add. I hate that there's no option to set different partition schemes with their board definition. Alternatively: I've copied what they set in pins_arduino.h anyway, so could just tell people to select a generic ESP32 board instead.
