### ISSUE TITLE
UiDemo not working

### ISSUE THREAD

**Issue by Zep0** [ropg/heltec_esp32_lora_v3#58]
Hey,
first of all, thank you very much for this library!
Unfortunately I can't get the UiDemo to run. The display shows nothing. However, the other OLED demos work.

Heltec Wifi LoRa 32 V3 (HTIT-WB32LAF)
Arduino IDE 2.3.3
Library version 0.9.2
Ubuntu 22.04

**Comment by decodeais** [comment]
it works if you add the command at the beginninig heltec_setup().
```
void setup() {
  heltec_setup();
  Serial.begin(115200);
  Serial.println();
  Serial.println();
......

**Comment by ropg** [comment]
Oh, whoops... Fixed...

**Comment by ropg** [comment]
(Also don't need the `Serial.begin then)

Thanks @Zep0 !
